package com.yourname.loopypowers.sound;

import com.yourname.loopypowers.Loopypowers;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;

public final class ModSounds {

    // IDs
    public static final Identifier THUNDERCLAP_ID     = new Identifier(Loopypowers.MOD_ID, "thunderclap");
    public static final Identifier TELEPORTCLAP_ID    = new Identifier(Loopypowers.MOD_ID, "teleportclap");
    public static final Identifier TELEPORTSNAP_ID    = new Identifier(Loopypowers.MOD_ID, "teleportsnap");
    public static final Identifier DASH_ID            = new Identifier(Loopypowers.MOD_ID, "dash");
    public static final Identifier RUSHSTART_ID       = new Identifier(Loopypowers.MOD_ID, "rushstart");
    public static final Identifier RUSHLOOP_ID        = new Identifier(Loopypowers.MOD_ID, "rushloop");
    public static final Identifier OVERDRIVESTART_ID  = new Identifier(Loopypowers.MOD_ID, "overdrivestart");
    public static final Identifier OVERDRIVELOOP_ID   = new Identifier(Loopypowers.MOD_ID, "overdriveloop");
    public static final Identifier ELECTRICITY_ID     = new Identifier(Loopypowers.MOD_ID, "electricity");
    public static final Identifier RAGE_ID            = new Identifier(Loopypowers.MOD_ID, "rage");
    public static final Identifier BASSDROP_ID        = new Identifier(Loopypowers.MOD_ID, "bassdrop");
    public static final Identifier BASSSINGLE_ID      = new Identifier(Loopypowers.MOD_ID, "basssingle");
    public static final Identifier BULLRUSH_ID        = new Identifier(Loopypowers.MOD_ID, "bullrush");
    public static final Identifier EARRING_ID         = new Identifier(Loopypowers.MOD_ID, "earring");
    public static final Identifier ENTITYSLAM_ID      = new Identifier(Loopypowers.MOD_ID, "entityslam");
    public static final Identifier RAILGUN_ID         = new Identifier(Loopypowers.MOD_ID, "railgun");
    public static final Identifier SLAM_ID            = new Identifier(Loopypowers.MOD_ID, "slam");
    public static final Identifier THUNDERCLAP2_ID    = new Identifier(Loopypowers.MOD_ID, "thunderclap2");
    public static final Identifier THUNDERCLAP3_ID    = new Identifier(Loopypowers.MOD_ID, "thunderclap3");
    public static final Identifier WALLSLAM_ID        = new Identifier(Loopypowers.MOD_ID, "wallslam");
    public static final Identifier POSSESSION_ID      = new Identifier(Loopypowers.MOD_ID, "possession");
    public static final Identifier BULLRUSHSTOP_ID    = new Identifier(Loopypowers.MOD_ID, "bullrushstop");
    public static final Identifier LUNGESTART_ID      = new Identifier(Loopypowers.MOD_ID, "lungestart");
    public static final Identifier SHATTER_ID         = new Identifier(Loopypowers.MOD_ID, "shatter");
    public static final Identifier SHOCK_ID           = new Identifier(Loopypowers.MOD_ID, "shock");
    public static final Identifier BACKSTAB_ID        = new Identifier(Loopypowers.MOD_ID, "backstab");
    public static final Identifier BIGSTAB_ID         = new Identifier(Loopypowers.MOD_ID, "bigstab");
    public static final Identifier BASSBURST_ID       = new Identifier(Loopypowers.MOD_ID, "bassburst");
    public static final Identifier ARENABUILD_ID      = new Identifier(Loopypowers.MOD_ID, "arenabuild");
    public static final Identifier BOLT_ID            = new Identifier(Loopypowers.MOD_ID, "bolt");
    public static final Identifier EXPLODEBIG_ID      = new Identifier(Loopypowers.MOD_ID, "explodebig");
    public static final Identifier SPRAY_ID           = new Identifier(Loopypowers.MOD_ID, "spray");
    public static final Identifier VINELASH_ID        = new Identifier(Loopypowers.MOD_ID, "vinelash");
    public static final Identifier BLIZZARDLOOP_ID    = new Identifier(Loopypowers.MOD_ID, "blizzardloop");
    public static final Identifier SPIKECAST_ID       = new Identifier(Loopypowers.MOD_ID, "spikecast");
    public static final Identifier DARKNESSLOOP_ID    = new Identifier(Loopypowers.MOD_ID, "darknessloop");
    public static final Identifier ICEBEAMLOOP_ID     = new Identifier(Loopypowers.MOD_ID, "icebeamloop");
    public static final Identifier ICEBEAMCHARGE_ID   = new Identifier(Loopypowers.MOD_ID, "icebeamcharge");
    public static final Identifier RAISESTAKES_ID     = new Identifier(Loopypowers.MOD_ID, "raisestakes");
    public static final Identifier ALLIN_ID           = new Identifier(Loopypowers.MOD_ID, "allin");
    public static final Identifier JACKPOT_ID         = new Identifier(Loopypowers.MOD_ID, "jackpot");
    public static final Identifier JACKPOT2_ID        = new Identifier(Loopypowers.MOD_ID, "jackpot2");
    public static final Identifier JACKPOT3_ID        = new Identifier(Loopypowers.MOD_ID, "jackpot3");
    public static final Identifier NEWRULE_ID         = new Identifier(Loopypowers.MOD_ID, "newrule");
    public static final Identifier FLICKER_ID         = new Identifier(Loopypowers.MOD_ID, "flicker");
    public static final Identifier FLICKER2_ID        = new Identifier(Loopypowers.MOD_ID, "flicker2");
    public static final Identifier FLICKER3_ID        = new Identifier(Loopypowers.MOD_ID, "flicker3");
    public static final Identifier DARKNESSTELEPORT_ID = new Identifier(Loopypowers.MOD_ID, "darknessteleport");
    public static final Identifier MISTENTER_ID       = new Identifier(Loopypowers.MOD_ID, "mistenter");
    public static final Identifier MISTLOOP_ID        = new Identifier(Loopypowers.MOD_ID, "mistloop");
    public static final Identifier DARKNESSTELEPORT2_ID = new Identifier(Loopypowers.MOD_ID, "darknessteleport2");
    public static final Identifier SUSPEND_ID         = new Identifier(Loopypowers.MOD_ID, "suspend");
    public static final Identifier BLACKHOLELOOP_ID   = new Identifier(Loopypowers.MOD_ID, "blackholeloop");
    public static final Identifier YANK_ID            = new Identifier(Loopypowers.MOD_ID, "yank");
    public static final Identifier GUST_ID            = new Identifier(Loopypowers.MOD_ID, "gust");
    public static final Identifier UPDRAFT_ID         = new Identifier(Loopypowers.MOD_ID, "updraft");
    public static final Identifier RITUALLOOP_ID      = new Identifier(Loopypowers.MOD_ID, "ritualloop");
    public static final Identifier RITUALSTART_ID     = new Identifier(Loopypowers.MOD_ID, "ritualstart");
    public static final Identifier COSMICRAY_ID       = new Identifier(Loopypowers.MOD_ID, "cosmicray");
    public static final Identifier JACKPOTFUNNY_ID    = new Identifier(Loopypowers.MOD_ID, "jackpotfunny");
    public static final Identifier PARTYPOPPER_ID     = new Identifier(Loopypowers.MOD_ID, "partypopper");
    public static final Identifier FUNNYFNAF_ID       = new Identifier(Loopypowers.MOD_ID, "funnyfnaf");
    public static final Identifier ONEPUNCH_ID        = new Identifier(Loopypowers.MOD_ID, "onepunch");
    public static final Identifier HECANFLY_ID        = new Identifier(Loopypowers.MOD_ID, "hecanfly");
    public static final Identifier PVZPOP_ID          = new Identifier(Loopypowers.MOD_ID, "pvzpop");
    public static final Identifier MEDIC_ID           = new Identifier(Loopypowers.MOD_ID, "medic");
    public static final Identifier STINK_ID           = new Identifier(Loopypowers.MOD_ID, "stink");
    public static final Identifier WHY_ID           = new Identifier(Loopypowers.MOD_ID, "why");

    // SoundEvents
    public static final SoundEvent THUNDERCLAP     = SoundEvent.of(THUNDERCLAP_ID);
    public static final SoundEvent TELEPORTCLAP    = SoundEvent.of(TELEPORTCLAP_ID);
    public static final SoundEvent TELEPORTSNAP    = SoundEvent.of(TELEPORTSNAP_ID);
    public static final SoundEvent DASH            = SoundEvent.of(DASH_ID);
    public static final SoundEvent RUSHSTART       = SoundEvent.of(RUSHSTART_ID);
    public static final SoundEvent RUSHLOOP        = SoundEvent.of(RUSHLOOP_ID);
    public static final SoundEvent OVERDRIVESTART  = SoundEvent.of(OVERDRIVESTART_ID);
    public static final SoundEvent OVERDRIVELOOP   = SoundEvent.of(OVERDRIVELOOP_ID);
    public static final SoundEvent ELECTRICITY     = SoundEvent.of(ELECTRICITY_ID);
    public static final SoundEvent RAGE            = SoundEvent.of(RAGE_ID);
    public static final SoundEvent BASSDROP        = SoundEvent.of(BASSDROP_ID);
    public static final SoundEvent BASSSINGLE      = SoundEvent.of(BASSSINGLE_ID);
    public static final SoundEvent BULLRUSH        = SoundEvent.of(BULLRUSH_ID);
    public static final SoundEvent EARRING         = SoundEvent.of(EARRING_ID);
    public static final SoundEvent ENTITYSLAM      = SoundEvent.of(ENTITYSLAM_ID);
    public static final SoundEvent RAILGUN         = SoundEvent.of(RAILGUN_ID);
    public static final SoundEvent SLAM            = SoundEvent.of(SLAM_ID);
    public static final SoundEvent WALLSLAM        = SoundEvent.of(WALLSLAM_ID);
    public static final SoundEvent POSSESSION      = SoundEvent.of(POSSESSION_ID);
    public static final SoundEvent BULLRUSHSTOP    = SoundEvent.of(BULLRUSHSTOP_ID);
    public static final SoundEvent LUNGESTART      = SoundEvent.of(LUNGESTART_ID);
    public static final SoundEvent SHATTER         = SoundEvent.of(SHATTER_ID);
    public static final SoundEvent SHOCK           = SoundEvent.of(SHOCK_ID);
    public static final SoundEvent BACKSTAB        = SoundEvent.of(BACKSTAB_ID);
    public static final SoundEvent BIGSTAB         = SoundEvent.of(BIGSTAB_ID);
    public static final SoundEvent BASSBURST       = SoundEvent.of(BASSBURST_ID);
    public static final SoundEvent ARENABUILD      = SoundEvent.of(ARENABUILD_ID);
    public static final SoundEvent BOLT            = SoundEvent.of(BOLT_ID);
    public static final SoundEvent EXPLODEBIG      = SoundEvent.of(EXPLODEBIG_ID);
    public static final SoundEvent SPRAY           = SoundEvent.of(SPRAY_ID);
    public static final SoundEvent VINELASH        = SoundEvent.of(VINELASH_ID);
    public static final SoundEvent BLIZZARDLOOP    = SoundEvent.of(BLIZZARDLOOP_ID);
    public static final SoundEvent SPIKECAST       = SoundEvent.of(SPIKECAST_ID);
    public static final SoundEvent DARKNESSLOOP    = SoundEvent.of(DARKNESSLOOP_ID);
    public static final SoundEvent ICEBEAMLOOP     = SoundEvent.of(ICEBEAMLOOP_ID);
    public static final SoundEvent ICEBEAMCHARGE   = SoundEvent.of(ICEBEAMCHARGE_ID);
    public static final SoundEvent RAISESTAKES     = SoundEvent.of(RAISESTAKES_ID);
    public static final SoundEvent ALLIN           = SoundEvent.of(ALLIN_ID);
    public static final SoundEvent JACKPOT         = SoundEvent.of(JACKPOT_ID);
    public static final SoundEvent JACKPOT2        = SoundEvent.of(JACKPOT2_ID);
    public static final SoundEvent JACKPOT3        = SoundEvent.of(JACKPOT3_ID);
    public static final SoundEvent NEWRULE         = SoundEvent.of(NEWRULE_ID);
    public static final SoundEvent FLICKER         = SoundEvent.of(FLICKER_ID);
    public static final SoundEvent FLICKER2        = SoundEvent.of(FLICKER2_ID);
    public static final SoundEvent FLICKER3        = SoundEvent.of(FLICKER3_ID);
    public static final SoundEvent DARKNESSTELEPORT= SoundEvent.of(DARKNESSTELEPORT_ID);
    public static final SoundEvent MISTENTER       = SoundEvent.of(MISTENTER_ID);
    public static final SoundEvent MISTLOOP        = SoundEvent.of(MISTLOOP_ID);
    public static final SoundEvent DARKNESSTELEPORT2= SoundEvent.of(DARKNESSTELEPORT2_ID);
    public static final SoundEvent SUSPEND         = SoundEvent.of(SUSPEND_ID);
    public static final SoundEvent BLACKHOLELOOP   = SoundEvent.of(BLACKHOLELOOP_ID);
    public static final SoundEvent YANK            = SoundEvent.of(YANK_ID);
    public static final SoundEvent GUST            = SoundEvent.of(GUST_ID);
    public static final SoundEvent UPDRAFT         = SoundEvent.of(UPDRAFT_ID);
    public static final SoundEvent RITUALLOOP      = SoundEvent.of(RITUALLOOP_ID);
    public static final SoundEvent RITUALSTART     = SoundEvent.of(RITUALSTART_ID);
    public static final SoundEvent COSMICRAY       = SoundEvent.of(COSMICRAY_ID);
    public static final SoundEvent JACKPOTFUNNY    = SoundEvent.of(JACKPOTFUNNY_ID);
    public static final SoundEvent PARTYPOPPER     = SoundEvent.of(PARTYPOPPER_ID);
    public static final SoundEvent FUNNYFNAF       = SoundEvent.of(FUNNYFNAF_ID);
    public static final SoundEvent ONEPUNCH        = SoundEvent.of(ONEPUNCH_ID);
    public static final SoundEvent HECANFLY        = SoundEvent.of(HECANFLY_ID);
    public static final SoundEvent PVZPOP          = SoundEvent.of(PVZPOP_ID);
    public static final SoundEvent MEDIC           = SoundEvent.of(MEDIC_ID);
    public static final SoundEvent STINK           = SoundEvent.of(STINK_ID);
    public static final SoundEvent WHY           = SoundEvent.of(WHY_ID);

    private ModSounds() {}

    public static void register() {
        Registry.register(Registries.SOUND_EVENT, THUNDERCLAP_ID, THUNDERCLAP);
        Registry.register(Registries.SOUND_EVENT, TELEPORTCLAP_ID, TELEPORTCLAP);
        Registry.register(Registries.SOUND_EVENT, TELEPORTSNAP_ID, TELEPORTSNAP);
        Registry.register(Registries.SOUND_EVENT, DASH_ID, DASH);
        Registry.register(Registries.SOUND_EVENT, RUSHSTART_ID, RUSHSTART);
        Registry.register(Registries.SOUND_EVENT, RUSHLOOP_ID, RUSHLOOP);
        Registry.register(Registries.SOUND_EVENT, OVERDRIVESTART_ID, OVERDRIVESTART);
        Registry.register(Registries.SOUND_EVENT, OVERDRIVELOOP_ID, OVERDRIVELOOP);
        Registry.register(Registries.SOUND_EVENT, ELECTRICITY_ID, ELECTRICITY);
        Registry.register(Registries.SOUND_EVENT, RAGE_ID, RAGE);
        Registry.register(Registries.SOUND_EVENT, BASSDROP_ID, BASSDROP);
        Registry.register(Registries.SOUND_EVENT, BASSSINGLE_ID, BASSSINGLE);
        Registry.register(Registries.SOUND_EVENT, BULLRUSH_ID, BULLRUSH);
        Registry.register(Registries.SOUND_EVENT, EARRING_ID, EARRING);
        Registry.register(Registries.SOUND_EVENT, ENTITYSLAM_ID, ENTITYSLAM);
        Registry.register(Registries.SOUND_EVENT, RAILGUN_ID, RAILGUN);
        Registry.register(Registries.SOUND_EVENT, SLAM_ID, SLAM);
        Registry.register(Registries.SOUND_EVENT, WALLSLAM_ID, WALLSLAM);
        Registry.register(Registries.SOUND_EVENT, POSSESSION_ID, POSSESSION);
        Registry.register(Registries.SOUND_EVENT, BULLRUSHSTOP_ID, BULLRUSHSTOP);
        Registry.register(Registries.SOUND_EVENT, LUNGESTART_ID, LUNGESTART);
        Registry.register(Registries.SOUND_EVENT, SHATTER_ID, SHATTER);
        Registry.register(Registries.SOUND_EVENT, SHOCK_ID, SHOCK);
        Registry.register(Registries.SOUND_EVENT, BACKSTAB_ID, BACKSTAB);
        Registry.register(Registries.SOUND_EVENT, BIGSTAB_ID, BIGSTAB);
        Registry.register(Registries.SOUND_EVENT, BASSBURST_ID, BASSBURST);
        Registry.register(Registries.SOUND_EVENT, ARENABUILD_ID, ARENABUILD);
        Registry.register(Registries.SOUND_EVENT, BOLT_ID, BOLT);
        Registry.register(Registries.SOUND_EVENT, EXPLODEBIG_ID, EXPLODEBIG);
        Registry.register(Registries.SOUND_EVENT, SPRAY_ID, SPRAY);
        Registry.register(Registries.SOUND_EVENT, VINELASH_ID, VINELASH);
        Registry.register(Registries.SOUND_EVENT, BLIZZARDLOOP_ID, BLIZZARDLOOP);
        Registry.register(Registries.SOUND_EVENT, SPIKECAST_ID, SPIKECAST);
        Registry.register(Registries.SOUND_EVENT, DARKNESSLOOP_ID, DARKNESSLOOP);
        Registry.register(Registries.SOUND_EVENT, ICEBEAMLOOP_ID, ICEBEAMLOOP);
        Registry.register(Registries.SOUND_EVENT, ICEBEAMCHARGE_ID, ICEBEAMCHARGE);
        Registry.register(Registries.SOUND_EVENT, RAISESTAKES_ID, RAISESTAKES);
        Registry.register(Registries.SOUND_EVENT, ALLIN_ID, ALLIN);
        Registry.register(Registries.SOUND_EVENT, JACKPOT_ID, JACKPOT);
        Registry.register(Registries.SOUND_EVENT, JACKPOT2_ID, JACKPOT2);
        Registry.register(Registries.SOUND_EVENT, JACKPOT3_ID, JACKPOT3);
        Registry.register(Registries.SOUND_EVENT, NEWRULE_ID, NEWRULE);
        Registry.register(Registries.SOUND_EVENT, FLICKER_ID, FLICKER);
        Registry.register(Registries.SOUND_EVENT, FLICKER2_ID, FLICKER2);
        Registry.register(Registries.SOUND_EVENT, FLICKER3_ID, FLICKER3);
        Registry.register(Registries.SOUND_EVENT, DARKNESSTELEPORT_ID, DARKNESSTELEPORT);
        Registry.register(Registries.SOUND_EVENT, MISTENTER_ID, MISTENTER);
        Registry.register(Registries.SOUND_EVENT, MISTLOOP_ID, MISTLOOP);
        Registry.register(Registries.SOUND_EVENT, DARKNESSTELEPORT2_ID, DARKNESSTELEPORT2);
        Registry.register(Registries.SOUND_EVENT, SUSPEND_ID, SUSPEND);
        Registry.register(Registries.SOUND_EVENT, BLACKHOLELOOP_ID, BLACKHOLELOOP);
        Registry.register(Registries.SOUND_EVENT, YANK_ID, YANK);
        Registry.register(Registries.SOUND_EVENT, GUST_ID, GUST);
        Registry.register(Registries.SOUND_EVENT, UPDRAFT_ID, UPDRAFT);
        Registry.register(Registries.SOUND_EVENT, RITUALLOOP_ID, RITUALLOOP);
        Registry.register(Registries.SOUND_EVENT, RITUALSTART_ID, RITUALSTART);
        Registry.register(Registries.SOUND_EVENT, COSMICRAY_ID, COSMICRAY);
        Registry.register(Registries.SOUND_EVENT, JACKPOTFUNNY_ID, JACKPOTFUNNY);
        Registry.register(Registries.SOUND_EVENT, PARTYPOPPER_ID, PARTYPOPPER);
        Registry.register(Registries.SOUND_EVENT, FUNNYFNAF_ID, FUNNYFNAF);
        Registry.register(Registries.SOUND_EVENT, ONEPUNCH_ID, ONEPUNCH);
        Registry.register(Registries.SOUND_EVENT, HECANFLY_ID, HECANFLY);
        Registry.register(Registries.SOUND_EVENT, PVZPOP_ID, PVZPOP);
        Registry.register(Registries.SOUND_EVENT, MEDIC_ID, MEDIC);
        Registry.register(Registries.SOUND_EVENT, STINK_ID, STINK);
        Registry.register(Registries.SOUND_EVENT, WHY_ID, WHY);
    }
} // doing this sucks